import hashlib
import sys
from pathlib import Path


def get_base_dir() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path(__file__).resolve().parent.parent


BASE_DIR = get_base_dir()
CONFIG_PATH = BASE_DIR / "config.json"
DEFAULT_MODEL = "models/gemini-3.1-flash-lite-preview"
DEFAULT_BASE_URL = "https://generativelanguage.googleapis.com"
DEFAULT_OPENAI_BASE_URL = "https://api.openai.com"
APP_LOCK_PATH = str(BASE_DIR / ".ocrtranslator.lock")
LOCK_STALE_MS = 15000
APP_SERVER_NAME = f"ocrtranslator-{hashlib.md5(str(BASE_DIR).encode('utf-8')).hexdigest()}"
MODEL_PREFIX = "models/"
PROVIDER_LABELS = {
    "gemini": {"zh-TW": "Gemini 相容", "en": "Gemini Compatible"},
    "openai": {"zh-TW": "OpenAI 相容", "en": "OpenAI Compatible"},
}
DEFAULT_PROMPT = (
    "You will receive a screenshot that may contain text in any language. "
    "Please do the following directly:\n"
    "1. Recognize the text in the image;\n"
    "2. Translate it into the specified target language;\n"
    "3. Preserve paragraph order and reading order as much as possible;\n"
    "4. Do not explain, do not add preface, and do not output the original text;\n"
    "5. If some text is unclear, translate as much as possible based on visible content and mark it as partially unclear;\n"
    "6. Output clean translated text suitable for direct reading."
)

I18N = {
    "zh-TW": {
        "window_title": "OCR 翻譯器",
        "title": "多語 OCR 翻譯工具",
        "subtitle": "為閱讀、研究與日常螢幕內容翻譯打造的桌面 OCR 翻譯工作台",
        "navigation": "導航",
        "quick_actions": "快速操作",
        "api_keys_hidden": "API Keys（已隱藏）",
        "show_api_keys": "顯示 Key",
        "hide_api_keys": "隱藏 Key",
        "api_keys_mask_hint": "API Key 預設遮罩顯示；按右側按鈕可切換顯示後再編輯。",
        "tab_settings": "設定",
        "tab_monitor": "預覽與 Log",
        "section_profiles": "設定檔管理",
        "section_api": "API 連線設定",
        "section_reading": "閱讀與翻譯設定",
        "section_advanced": "進階顯示與請求設定",
        "section_preview_logs": "預覽與即時 Log",
        "profile": "API 設定檔",
        "sidebar_hint_title": "使用提示",
        "new_profile": "新增設定檔",
        "page_settings_title": "OCR 工作台設定",
        "page_settings_subtitle": "整理 API 設定檔、閱讀偏好與全域快捷鍵，讓截圖翻譯保持輕巧順手。",
        "page_monitor_title": "預覽與執行狀態",
        "page_monitor_subtitle": "查看最近一次截圖預覽與記憶體中的執行紀錄，快速確認目前流程是否正常。",
        "meta_hotkey": "快捷鍵 {value}",
        "meta_target": "目標 {value}",
        "meta_mode": "模式 {value}",
        "preview_panel": "最近截圖預覽",
        "activity_panel": "活動紀錄",
        "delete_profile": "刪除設定檔",
        "profile_name_template": "設定檔 {index}",
        "untitled_profile": "未命名設定檔",
        "profile_name_exists": "設定檔名稱已存在：{name}",
        "profile_name": "設定檔名稱",
        "provider": "相容格式",
        "base_url": "Base URL",
        "api_keys": "API Keys",
        "profile_name_placeholder": "例如：Default Gemini / Work Account",
        "base_url_placeholder": "輸入相容 API 的根地址",
        "model_placeholder": "輸入模型名稱，或先獲取模型列表",
        "target_language_placeholder": "例如：繁體中文 / English / 日本語",
        "hotkey_placeholder": "例如：Shift+Win+A",
        "api_keys_placeholder": "每行一個 API Key",
        "record_hotkey": "录制快捷键",
        "recording_hotkey": "按下组合键…",
        "api_keys_hint": "每行一個 Key，同一個 URL 會自動輪循。",
        "model": "模型",
        "fetch_models": "獲取模型列表",
        "test_api": "測試 API",
        "target_language": "目標語言",
        "ui_language": "介面語言",
        "display_mode": "顯示模式",
        "hotkey": "全域快捷鍵",
        "overlay_font_family": "翻譯字型",
        "overlay_font_size": "翻譯字級",
        "retry_count": "重試次數",
        "retry_interval": "重試間隔(秒)",
        "temperature": "模型溫度",
        "overlay_width": "浮窗基準寬度",
        "overlay_height": "浮窗基準高度",
        "overlay_margin": "浮窗邊距",
        "save_settings": "儲存設定",
        "start_capture": "開始框選截圖",
        "minimize_to_tray": "最小化到系統匣",
        "mode_book_lr": "雙頁左右(book_lr)",
        "mode_web_ud": "網頁上下(web_ud)",
        "hint": "提示：X 會直接退出程式；只有按「最小化到系統匣」才會進入系統匣。",
        "ready": "準備就緒",
        "settings_saved": "設定已儲存",
        "capturing": "截圖完成，正在請求模型翻譯...",
        "translated": "翻譯完成",
        "translate_failed": "翻譯失敗",
        "operation_failed": "操作失敗",
        "validation_failed": "請先修正紅色標記的欄位。",
        "hotkey_recording": "請直接按下新的快捷鍵組合",
        "hotkey_recorded": "快捷鍵已錄製：{hotkey}",
        "hotkey_record_cancelled": "已取消快捷鍵錄製",
        "overlay_title": "翻譯結果",
        "empty_result": "模型沒有回傳可顯示的內容。",
        "overlay_pin_short": "Pin",
        "overlay_pinned_short": "已 Pin",
        "toggle_overlay_pin": "切換是否保留浮窗",
        "decrease_overlay_opacity": "降低浮窗透明度",
        "increase_overlay_opacity": "提高浮窗透明度",
        "cycle_overlay_opacity": "循環切換浮窗透明度",
        "tray_title": "OCR 翻譯器",
        "tray_show": "顯示主視窗",
        "tray_capture": "開始截圖",
        "tray_quit": "退出",
        "overlay_pinned": "翻譯浮窗已固定保留",
        "overlay_unpinned": "翻譯浮窗已取消固定",
        "overlay_opacity_set": "浮窗透明度已調整為 {value}%",
        "validation_base_url_required": "請先填寫 Base URL。",
        "validation_base_url_scheme": "Base URL 必須以 http:// 或 https:// 開頭。",
        "validation_model_required": "請先填寫模型名稱。",
        "validation_api_keys_required": "至少要提供一個 API Key。",
        "validation_target_language_required": "請先填寫目標語言。",
        "validation_hotkey_required": "請先設定全域快捷鍵。",
        "validation_hotkey_invalid": "快捷鍵格式無效：{error}",
        "validation_hotkey_requires_modifier": "快捷鍵至少要包含一個修飾鍵（Ctrl / Alt / Shift / Win）。",
        "validation_hotkey_recording": "請先完成快捷鍵錄製，或按 Esc 取消。",
        "tray_minimized": "已最小化到系統匣。",
        "tray_capturing": "已截圖，正在翻譯中...",
        "tray_unavailable": "目前環境沒有可用的系統匣，無法最小化到系統匣。",
        "error_title": "錯誤",
        "hotkey_registered": "快捷鍵已更新：{hotkey}",
        "hotkey_register_failed": "快捷鍵註冊失敗：{error}",
        "language_saved": "語言已切換並儲存",
        "logs": "即時 Log（最近 100 條，不落地保存）",
        "test_success": "API 測試成功。",
        "models_loaded": "已獲取 {count} 個模型。",
        "profile_deleted": "已刪除設定檔：{name}",
        "confirm_delete_profile": "確定要刪除設定檔「{name}」嗎？",
        "at_least_one_profile": "至少要保留一個設定檔。",
        "capture_cancelled": "已取消截圖。",
        "font_zoomed": "翻譯字級已調整為 {size}",
        "already_running_title": "程式已在執行",
        "clear_logs": "清空紀錄",
        "logs_empty": "目前還沒有執行紀錄。先截圖或測試 API，這裡就會開始累積內容。",
        "logs_cleared": "已清空活動紀錄。",
        "export_logs": "匯出紀錄",
        "export_logs_dialog_title": "匯出執行紀錄",
        "export_logs_filter": "文字檔 (*.txt);;所有檔案 (*.*)",
        "logs_export_empty": "目前沒有可匯出的活動紀錄。",
        "logs_exported": "活動紀錄已匯出：{path}",
        "selection_hint": "拖曳選取區域  ·  Esc / 右鍵取消",
        "copy_translation": "複製結果",
        "already_running_message": "OCR 翻譯器已在執行中。\n\n請先檢查系統匣，或關閉既有視窗後再重試。",
        "overlay_copied": "翻譯結果已複製到剪貼簿",
        "unsaved_changes_title": "尚未儲存的變更",
        "unsaved_changes_message": "目前有尚未儲存的變更。要先儲存再繼續嗎？",
        "unsaved_changes_save": "儲存後繼續",
        "unsaved_changes_discard": "捨棄變更",
        "unsaved_changes_cancel": "取消",
        "fetch_models_busy": "獲取中...",
        "test_api_busy": "測試中...",
        "start_capture_busy": "翻譯中...",
        "preview_placeholder": "完成一次截圖後，這裡會顯示最近的畫面預覽。",
    },
    "en": {
        "window_title": "OCR Translator",
        "title": "Multilingual OCR Translator",
        "subtitle": "A desktop OCR translation workspace for reading, research, and everyday on-screen text",
        "navigation": "Navigation",
        "quick_actions": "Quick Actions",
        "api_keys_hidden": "API Keys (Hidden)",
        "show_api_keys": "Show Keys",
        "hide_api_keys": "Hide Keys",
        "api_keys_mask_hint": "API keys are masked by default. Click the button on the right to reveal and edit them.",
        "tab_settings": "Settings",
        "tab_monitor": "Preview & Log",
        "section_profiles": "Profile Management",
        "section_api": "API Connection Settings",
        "section_reading": "Reading & Translation Settings",
        "section_advanced": "Advanced Display & Request Settings",
        "section_preview_logs": "Preview & Runtime Log",
        "profile": "API Profile",
        "sidebar_hint_title": "Usage Tip",
        "new_profile": "New Profile",
        "page_settings_title": "Workspace Settings",
        "page_settings_subtitle": "Tune API profiles, reading preferences, and the global hotkey in a calmer, more compact workspace.",
        "page_monitor_title": "Preview & Runtime State",
        "page_monitor_subtitle": "Inspect the latest capture preview and the in-memory runtime trail to confirm the workflow is behaving as expected.",
        "meta_hotkey": "Hotkey {value}",
        "meta_target": "Target {value}",
        "meta_mode": "Mode {value}",
        "preview_panel": "Latest Capture Preview",
        "activity_panel": "Activity Feed",
        "delete_profile": "Delete Profile",
        "profile_name_template": "Profile {index}",
        "untitled_profile": "Untitled Profile",
        "profile_name_exists": "Profile name already exists: {name}",
        "profile_name": "Profile Name",
        "provider": "Compatibility",
        "base_url": "Base URL",
        "api_keys": "API Keys",
        "profile_name_placeholder": "e.g. Default Gemini / Work Account",
        "base_url_placeholder": "Enter the compatible API root URL",
        "model_placeholder": "Enter a model name, or fetch the list first",
        "target_language_placeholder": "e.g. Traditional Chinese / English / Japanese",
        "hotkey_placeholder": "e.g. Shift+Win+A",
        "api_keys_placeholder": "One API key per line",
        "record_hotkey": "Record Shortcut",
        "recording_hotkey": "Press keys…",
        "api_keys_hint": "One key per line. Keys under the same URL will rotate automatically.",
        "model": "Model",
        "fetch_models": "Fetch Models",
        "test_api": "Test API",
        "target_language": "Target Language",
        "ui_language": "UI Language",
        "display_mode": "Display Mode",
        "hotkey": "Global Hotkey",
        "overlay_font_family": "Translation Font",
        "overlay_font_size": "Translation Font Size",
        "retry_count": "Retry Count",
        "retry_interval": "Retry Interval (s)",
        "temperature": "Model Temperature",
        "overlay_width": "Overlay Base Width",
        "overlay_height": "Overlay Base Height",
        "overlay_margin": "Overlay Margin",
        "save_settings": "Save Settings",
        "start_capture": "Start Screen Capture",
        "minimize_to_tray": "Minimize to Tray",
        "mode_book_lr": "Dual-page Left/Right (book_lr)",
        "mode_web_ud": "Top/Bottom Web (web_ud)",
        "hint": "Tip: clicking X exits the app directly. Only the tray button minimizes it to the system tray.",
        "ready": "Ready",
        "settings_saved": "Settings saved",
        "capturing": "Screenshot captured, requesting translation...",
        "translated": "Translation completed",
        "translate_failed": "Translation failed",
        "operation_failed": "Operation failed",
        "validation_failed": "Please fix the highlighted fields first.",
        "hotkey_recording": "Press the new shortcut combination now",
        "hotkey_recorded": "Shortcut recorded: {hotkey}",
        "hotkey_record_cancelled": "Shortcut recording cancelled",
        "overlay_title": "Translation",
        "empty_result": "The model returned no displayable content.",
        "overlay_pin_short": "Pin",
        "overlay_pinned_short": "Pinned",
        "toggle_overlay_pin": "Toggle keeping the overlay visible",
        "decrease_overlay_opacity": "Decrease overlay opacity",
        "increase_overlay_opacity": "Increase overlay opacity",
        "cycle_overlay_opacity": "Cycle overlay opacity",
        "tray_title": "OCR Translator",
        "tray_show": "Show Window",
        "tray_capture": "Capture Screen",
        "tray_quit": "Quit",
        "overlay_pinned": "Translation overlay pinned",
        "overlay_unpinned": "Translation overlay unpinned",
        "overlay_opacity_set": "Overlay opacity changed to {value}%",
        "validation_base_url_required": "Please enter a Base URL.",
        "validation_base_url_scheme": "Base URL must start with http:// or https://.",
        "validation_model_required": "Please enter a model name.",
        "validation_api_keys_required": "At least one API key is required.",
        "validation_target_language_required": "Please enter a target language.",
        "validation_hotkey_required": "Please configure a global shortcut.",
        "validation_hotkey_invalid": "Invalid shortcut format: {error}",
        "validation_hotkey_requires_modifier": "The shortcut must include at least one modifier key (Ctrl / Alt / Shift / Win).",
        "validation_hotkey_recording": "Finish recording the shortcut first, or press Esc to cancel.",
        "tray_minimized": "Minimized to system tray.",
        "tray_capturing": "Screenshot captured. Translating...",
        "tray_unavailable": "System tray is unavailable in this environment, so the app cannot be minimized to tray.",
        "error_title": "Error",
        "hotkey_registered": "Hotkey updated: {hotkey}",
        "hotkey_register_failed": "Hotkey registration failed: {error}",
        "language_saved": "Language switched and saved",
        "logs": "Runtime Log (latest 100 entries, memory only)",
        "test_success": "API test succeeded.",
        "models_loaded": "Loaded {count} models.",
        "profile_deleted": "Deleted profile: {name}",
        "confirm_delete_profile": "Delete profile '{name}'?",
        "at_least_one_profile": "At least one profile must remain.",
        "capture_cancelled": "Capture cancelled.",
        "font_zoomed": "Translation font size changed to {size}",
        "already_running_title": "Already Running",
        "clear_logs": "Clear Activity",
        "logs_empty": "No runtime activity yet. Start a capture or test the API and entries will appear here.",
        "logs_cleared": "Activity log cleared.",
        "export_logs": "Export Log",
        "export_logs_dialog_title": "Export Runtime Log",
        "export_logs_filter": "Text Files (*.txt);;All Files (*.*)",
        "logs_export_empty": "There is no runtime activity to export yet.",
        "logs_exported": "Runtime log exported: {path}",
        "selection_hint": "Drag to select an area  ·  Esc / right-click to cancel",
        "copy_translation": "Copy Result",
        "already_running_message": "OCR Translator is already running.\n\nPlease check the system tray or close the existing window before launching again.",
        "overlay_copied": "Translation copied to clipboard",
        "unsaved_changes_title": "Unsaved Changes",
        "unsaved_changes_message": "You have unsaved changes. Save them before continuing?",
        "unsaved_changes_save": "Save and Continue",
        "unsaved_changes_discard": "Discard Changes",
        "unsaved_changes_cancel": "Cancel",
        "fetch_models_busy": "Fetching...",
        "test_api_busy": "Testing...",
        "start_capture_busy": "Translating...",
        "preview_placeholder": "Your latest screenshot preview will appear here after a capture finishes.",
    },
}
