from .app_defaults import (
    DEFAULT_BASE_URL,
    DEFAULT_CAPTURE_HOTKEY,
    DEFAULT_INPUT_HOTKEY,
    DEFAULT_MODEL,
    DEFAULT_OPENAI_BASE_URL,
    DEFAULT_OVERLAY_FONT_FAMILY,
    DEFAULT_SELECTION_HOTKEY,
    DEFAULT_TARGET_LANGUAGE,
    DEFAULT_UI_LANGUAGE,
    MODEL_PREFIX,
    PROVIDER_LABELS,
)
from .app_metadata import AUTHOR_NAME_EN, AUTHOR_NAME_ZH, REPOSITORY_NAME, REPOSITORY_URL
from .default_prompts import DEFAULT_PROMPT, DEFAULT_PROMPT_PRESET_DEFINITIONS, DEFAULT_TRANSLATION_IMAGE_PROMPT
from .i18n import I18N
from .runtime_paths import APP_LOCK_PATH, APP_SERVER_NAME, BASE_DIR, CONFIG_PATH, LOCK_STALE_MS, get_base_dir

__all__ = [
    "APP_LOCK_PATH",
    "APP_SERVER_NAME",
    "AUTHOR_NAME_EN",
    "AUTHOR_NAME_ZH",
    "BASE_DIR",
    "CONFIG_PATH",
    "DEFAULT_BASE_URL",
    "DEFAULT_CAPTURE_HOTKEY",
    "DEFAULT_INPUT_HOTKEY",
    "DEFAULT_MODEL",
    "DEFAULT_OPENAI_BASE_URL",
    "DEFAULT_OVERLAY_FONT_FAMILY",
    "DEFAULT_PROMPT",
    "DEFAULT_PROMPT_PRESET_DEFINITIONS",
    "DEFAULT_SELECTION_HOTKEY",
    "DEFAULT_TARGET_LANGUAGE",
    "DEFAULT_TRANSLATION_IMAGE_PROMPT",
    "DEFAULT_UI_LANGUAGE",
    "I18N",
    "LOCK_STALE_MS",
    "MODEL_PREFIX",
    "PROVIDER_LABELS",
    "REPOSITORY_NAME",
    "REPOSITORY_URL",
    "get_base_dir",
]
